name: CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  enviar-registro-docker:
    name: enviar Dockerimage para registro privado
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Construir & enviar Docker image
        with:
          image: mezali/php-app
          tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy_prod:
    name: enviar para a maquina remota
    runs-on: ubuntu-latest
    needs: enviar-registro-docker
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.CHAVE_PUBLICA_SSH }}
          port: 22
          script: |
            sudo docker stop php-app && sudo docker rm php-app && sudo docker image rm mezali/php-app:v1;
            sudo docker pull mezali/php-app:v1;
            sudo docker run -d --network loadbalancer --name=php-app-1 -h php-app-1 mezali/php-app:v1
            sudo docker run -d --network loadbalancer --name=php-app-2 -h php-app-2 mezali/php-app:v1
            sudo docker run -d --network loadbalancer --name=php-app-3 -h php-app-3 mezali/php-app:v1