name: CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  enviar-registro-docker:
    name: enviar Dockerimage para registro privado
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Construir & enviar Docker image
        with:
          image: mezali/php-app
          tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy_prod:
    name: enviar para a maquina remota
    runs-on: ubuntu-latest
    needs: enviar-registro-docker
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: 139.144.62.153
          username: root
          key: ${{ secrets.CHAVE_PUBLICA_SSH }}
          port: 22
          script: |
            docker service update --image mezali/php-app:v1 php-app
                                    